doctrine:
    dbal:
        driver: 'pdo_mysql'
        server_version: '5.6'
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: 'UTF8'
        mapping_types:
          enum: string

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        auto_mapping: false
        naming_strategy: 'doctrine.orm.naming_strategy.underscore'
        mappings:
            user:
                mapping: true
                type: 'annotation'
                dir: '%huel.domain_bundle.src_dir%/Domain/User/Model'
                prefix: 'Domain\User\Model'
                alias: 'Model'
                is_bundle: false
            icon:
                mapping: true
                type: 'annotation'
                dir: '%huel.domain_bundle.src_dir%/Domain/Icon/Model'
                prefix: 'Domain\Icon\Model'
                alias: 'Model'
                is_bundle: false
            banner:
                mapping: true
                type: 'annotation'
                dir: '%huel.domain_bundle.src_dir%/Domain/BannerFeature/Model'
                prefix: 'Domain\BannerFeature\Model'
                alias: 'Model'
                is_bundle: false
            flavour:
                mapping: true
                type: 'annotation'
                dir: '%huel.domain_bundle.src_dir%/Domain/Flavour/Model'
                prefix: 'Domain\Flavour\Model'
                alias: 'Model'
                is_bundle: false
            offer:
                mapping: true
                type: 'annotation'
                dir: '%huel.domain_bundle.src_dir%/Domain/Offer/Model'
                prefix: 'Domain\Offer\Model'
                alias: 'Model'
                is_bundle: false
            product:
                mapping: true
                type: 'annotation'
                dir: '%huel.domain_bundle.src_dir%/Domain/Product/Model'
                prefix: 'Domain\Product\Model'
                alias: 'Model'
                is_bundle: false
            discourse_topic:
                mapping: true
                type: 'annotation'
                dir: '%huel.domain_bundle.src_dir%/Domain/DiscourseTopic/Model'
                prefix: 'Domain\DiscourseTopic\Model'
                alias: 'Model'
                is_bundle: false
