security:
    providers:
        user_db:
            id: 'user_repository'

    encoders:
        Domain\User\Model\User:
            algorithm: 'bcrypt'
            cost: 12
#
#    role_hierarchy:
#        ROLE_ADMIN: 'ROLE_USER'
#        ROLE_SUPER_ADMIN: ['ROLE_USER', 'ROLE_ADMIN', 'ROLE_ALLOWED_TO_SWITCH']
